### ISSUE TITLE
按需引入 报错

### ISSUE THREAD

**Issue by suweien** [echaoo/mpx-echarts#2]
![image](https://user-images.githubusercontent.com/26915433/67543504-44ffaa00-f724-11e9-8b13-f2b16c0a849e.png)
![image](https://user-images.githubusercontent.com/26915433/67543507-4e891200-f724-11e9-8993-c6f3a2023fd9.png)
![image](https://user-images.githubusercontent.com/26915433/67543509-521c9900-f724-11e9-889a-401c7811bc20.png)

**Comment by suweien** [comment]
![image](https://user-images.githubusercontent.com/26915433/67543528-6791c300-f724-11e9-9641-abe5172b500b.png)

**Comment by echaoo** [comment]
app.mpx文件中引入你自己的echarts文件时这样引入：
`import * as echarts from './lib/echarts'`
因为你的echarts文件并没有export default 出来

**Comment by suweien** [comment]
嗯 谢谢 不报错了，不过 为啥我按需引入了以后 构建的为啥反而更大了，之前按照你的例子搞得不按需引入才1.2m  现在反而更大了= =
![image](https://user-images.githubusercontent.com/26915433/67644693-b5920b00-f95e-11e9-90f3-5db9dc78e953.png)
能麻烦给指个方向了，非常感谢

**Comment by echaoo** [comment]
npm run build 不会压缩，需要压缩的话你试试npm run prod
默认使用的echarts是压缩后的包
